-- Dbweb anonymous device credits, premium entitlements, redeem codes and manual UPI payments.
-- Run this once in Supabase SQL Editor after the original schema.sql.
create extension if not exists pgcrypto;
create table if not exists public.device_accounts(
 device_id uuid primary key, credits integer not null default 3 check(credits>=0), plan text not null default 'free',
 plan_expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.device_accounts alter column credits set default 3;
create table if not exists public.device_lookups(
 id bigint generated by default as identity primary key, device_id uuid not null references public.device_accounts(device_id) on delete cascade,
 lookup_type text not null check(lookup_type in ('number','aadhar')), query_hash text not null, created_at timestamptz not null default now()
);
create table if not exists public.redeem_codes(
 code_hash text primary key, code_preview text not null, credits_grant integer not null default 0 check(credits_grant>=0),
 premium_days integer not null default 0 check(premium_days>=0), max_uses integer not null default 1 check(max_uses>=1),
 uses_count integer not null default 0 check(uses_count>=0), expires_at timestamptz, active boolean not null default true,
 created_by text not null default 'admin', created_at timestamptz not null default now(), check(credits_grant>0 or premium_days>0)
);
create table if not exists public.device_redemptions(
 id bigint generated by default as identity primary key, code_hash text not null references public.redeem_codes(code_hash),
 device_id uuid not null references public.device_accounts(device_id) on delete cascade, redeemed_at timestamptz not null default now(),
 unique(code_hash,device_id)
);
create table if not exists public.device_payments(
 id bigint generated by default as identity primary key, device_id uuid not null references public.device_accounts(device_id),
 plan_days integer not null check(plan_days in (1,7,30)), amount integer not null check(amount in (30,100,300)),
 receipt_name text, receipt_path text, status text not null default 'pending' check(status in ('pending','approved','rejected')),
 reviewed_at timestamptz, reviewed_by text, created_at timestamptz not null default now(),
 check((plan_days=1 and amount=30) or (plan_days=7 and amount=100) or (plan_days=30 and amount=300))
);
alter table public.device_accounts enable row level security;
alter table public.device_lookups enable row level security;
alter table public.redeem_codes enable row level security;
alter table public.device_redemptions enable row level security;
alter table public.device_payments enable row level security;
-- No anon/authenticated policies: all access goes through server routes using service_role.
insert into storage.buckets(id,name,public) values('payment-receipts','payment-receipts',false) on conflict(id) do nothing;
create or replace function public.redeem_device_code(p_device_id uuid,p_code text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_hash text; v_code public.redeem_codes; v_account public.device_accounts; v_expiry timestamptz; v_message text;
begin
 -- p_code is a SHA-256 hex digest computed by the server API.
 v_hash:=lower(trim(p_code));
 select * into v_code from public.redeem_codes where code_hash=v_hash for update;
 if not found or not v_code.active then raise exception 'invalid code'; end if;
 if v_code.expires_at is not null and v_code.expires_at<=now() then raise exception 'code expired'; end if;
 if v_code.uses_count>=v_code.max_uses then raise exception 'code usage limit reached'; end if;
 if exists(select 1 from public.device_redemptions where code_hash=v_hash and device_id=p_device_id) then raise exception 'code already redeemed on this device'; end if;
 insert into public.device_accounts(device_id) values(p_device_id) on conflict(device_id) do nothing;
 select * into v_account from public.device_accounts where device_id=p_device_id for update;
 v_expiry:=case when v_code.premium_days>0 then greatest(coalesce(v_account.plan_expires_at,now()),now())+make_interval(days=>v_code.premium_days) else v_account.plan_expires_at end;
 update public.device_accounts set credits=credits+v_code.credits_grant,plan=case when v_code.premium_days>0 then v_code.premium_days||'d' else plan end,plan_expires_at=v_expiry,updated_at=now() where device_id=p_device_id;
 insert into public.device_redemptions(code_hash,device_id) values(v_hash,p_device_id);
 update public.redeem_codes set uses_count=uses_count+1 where code_hash=v_hash;
 v_message:=case when v_code.credits_grant>0 and v_code.premium_days>0 then v_code.credits_grant||' credits and '||v_code.premium_days||' premium days added.' when v_code.credits_grant>0 then v_code.credits_grant||' credits added.' else v_code.premium_days||' premium days added.' end;
 return jsonb_build_object('ok',true,'message',v_message);
end; $$;
revoke all on function public.redeem_device_code(uuid,text) from public,anon,authenticated;
grant execute on function public.redeem_device_code(uuid,text) to service_role;
