-- Dbweb / Supabase schema
-- Run this in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  credits integer not null default 10,
  plan text not null default 'free',
  plan_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.lookups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lookup_type text not null check (lookup_type in ('number','aadhar')),
  query_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_days integer not null check (plan_days in (1,7,30)),
  amount integer not null check (amount in (30,100,300)),
  receipt_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id,email,credits) values (new.id,new.email,10)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.lookups enable row level security;
alter table public.payments enable row level security;

create policy "profile own read" on public.profiles for select using (auth.uid() = id);
create policy "profile own update" on public.profiles for update using (auth.uid() = id);

create policy "lookup own read" on public.lookups for select using (auth.uid() = user_id);
create policy "lookup own insert" on public.lookups for insert with check (auth.uid() = user_id);

create policy "payment own read" on public.payments for select using (auth.uid() = user_id);
create policy "payment own insert" on public.payments for insert with check (auth.uid() = user_id);

-- Admin review should be performed with a server-side/admin connection.
-- Do not expose a Supabase service-role key in browser code.
