create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text, credits integer not null default 10, plan text not null default 'free',
  plan_expires_at timestamptz, created_at timestamptz not null default now()
);

create table if not exists public.lookups (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  lookup_type text not null check (lookup_type in ('number', 'aadhar')), query_hash text not null, created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  plan_days integer not null check (plan_days in (1,7,30)), amount integer not null check (amount in (30,100,300)),
  receipt_name text, receipt_path text, status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_at timestamptz, reviewed_by text, created_at timestamptz not null default now()
);

alter table public.payments add column if not exists receipt_path text;
alter table public.payments add column if not exists reviewed_at timestamptz;
alter table public.payments add column if not exists reviewed_by text;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,email,credits) values(new.id,new.email,10) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.lookups enable row level security;
alter table public.payments enable row level security;
drop policy if exists "profile own read" on public.profiles;
drop policy if exists "profile own update" on public.profiles;
drop policy if exists "lookup own read" on public.lookups;
drop policy if exists "lookup own insert" on public.lookups;
drop policy if exists "payment own read" on public.payments;
drop policy if exists "payment own insert" on public.payments;
create policy "profile own read" on public.profiles for select using(auth.uid()=id);
create policy "profile own update" on public.profiles for update using(auth.uid()=id);
create policy "lookup own read" on public.lookups for select using(auth.uid()=user_id);
create policy "lookup own insert" on public.lookups for insert with check(auth.uid()=user_id);
create policy "payment own read" on public.payments for select using(auth.uid()=user_id);
create policy "payment own insert" on public.payments for insert with check(auth.uid()=user_id);

insert into storage.buckets(id,name,public) values('payment-receipts','payment-receipts',false) on conflict(id) do nothing;

create or replace function public.approve_payment(p_payment_id bigint,p_admin_email text) returns public.payments
language plpgsql security definer set search_path=public as $$
declare v_payment public.payments; v_profile public.profiles; v_expiry timestamptz;
begin
  if lower(coalesce(p_admin_email,'')) <> lower('lumenomore@hotmail.com') then raise exception 'Not authorized'; end if;
  select * into v_payment from public.payments where id=p_payment_id for update;
  if not found then raise exception 'Payment not found'; end if;
  if v_payment.status <> 'pending' then raise exception 'Payment is already reviewed'; end if;
  select * into v_profile from public.profiles where id=v_payment.user_id for update;
  if not found then raise exception 'User profile not found'; end if;
  v_expiry := greatest(coalesce(v_profile.plan_expires_at,now()),now()) + make_interval(days=>v_payment.plan_days);
  update public.profiles set plan=v_payment.plan_days || 'd', plan_expires_at=v_expiry, credits=v_profile.credits+10 where id=v_payment.user_id;
  update public.payments set status='approved',reviewed_at=now(),reviewed_by=p_admin_email where id=p_payment_id returning * into v_payment;
  return v_payment;
end; $$;
revoke all on function public.approve_payment(bigint,text) from public;
revoke all on function public.approve_payment(bigint,text) from anon;
revoke all on function public.approve_payment(bigint,text) from authenticated;
grant execute on function public.approve_payment(bigint,text) to service_role;