'use client';
import {useEffect,useMemo,useState} from "react";
import {RefreshCw,LogOut,Gift,CreditCard,Check,X,Search,Copy,ShieldCheck,Clock3,Users,Wallet} from "lucide-react";
export default function AdminPage(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[payments,setPayments]=useState([]),[codes,setCodes]=useState([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(""),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[tab,setTab]=useState("overview"),[codeForm,setCodeForm]=useState({credits_grant:0,premium_days:7,max_uses:1,expires_at:""}),[grant,setGrant]=useState({device_id:"",credits:0,premium_days:30}),[newCode,setNewCode]=useState(""),[protectedNumbers,setProtectedNumbers]=useState([]),[protectedPhone,setProtectedPhone]=useState(""),[devices,setDevices]=useState([]),[deviceSearch,setDeviceSearch]=useState("");
 async function call(url,options={}){const r=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d;}
 async function load(){setLoading(true);try{const [p,c,n,d]=await Promise.all([call("/api/admin/payments"),call("/api/admin/redeem-codes"),call("/api/admin/protected-numbers"),call("/api/admin/devices")]);setPayments(p.payments||[]);setCodes(c.codes||[]);setProtectedNumbers(n.numbers||[]);setDevices(d.devices||[]);setMsg("");}catch(e){setMsg(e.message);}finally{setLoading(false);}}
 useEffect(()=>{call("/api/admin/session").then(async d=>{setOk(!!d.authenticated);if(d.authenticated)await load();}).catch(()=>{}).finally(()=>setReady(true));},[]);
 async function login(e){e.preventDefault();setBusy("login");try{await call("/api/admin/session",{method:"POST",body:JSON.stringify({password})});setOk(true);setPassword("");await load();}catch(e){setMsg(e.message);}finally{setBusy("");}}
 async function act(id,action){setBusy("payment-"+id);try{await call("/api/admin/payments",{method:"POST",body:JSON.stringify({payment_id:id,action})});setMsg("Payment #"+id+" "+(action==="approve"?"approved":"rejected")+".");await load();}catch(e){setMsg(e.message);}finally{setBusy("");}}
 async function createCode(e){e.preventDefault();setBusy("code");setMsg("");setNewCode("");try{const payload={...codeForm,credits_grant:Number(codeForm.credits_grant),premium_days:Number(codeForm.premium_days),max_uses:Number(codeForm.max_uses),expires_at:codeForm.expires_at?new Date(codeForm.expires_at).toISOString():null};const d=await call("/api/admin/redeem-codes",{method:"POST",body:JSON.stringify(payload)});setNewCode(d.code);setMsg("Redeem code created. Copy it now; the full code is shown only once.");await load();}catch(e){setMsg(e.message);}finally{setBusy("");}}
 async function giveAccess(e){e.preventDefault();setBusy("grant");setMsg("");try{const d=await call("/api/admin/grant",{method:"POST",body:JSON.stringify({...grant,credits:Number(grant.credits),premium_days:Number(grant.premium_days)})});setMsg("Access updated for "+grant.device_id+". "+d.message);setGrant(v=>({...v,device_id:""}));}catch(e){setMsg(e.message);}finally{setBusy("");}}
 async function protectAdminNumber(e){e.preventDefault();setBusy("protect");try{await call("/api/admin/protected-numbers",{method:"POST",body:JSON.stringify({phone:protectedPhone})});setProtectedPhone("");setMsg("Number protected.");await load();}catch(e){setMsg(e.message);}finally{setBusy("");}}
 async function unprotectNumber(phone){setBusy("unprotect");try{await call("/api/admin/protected-numbers",{method:"DELETE",body:JSON.stringify({phone})});setMsg("Protection removed.");await load();}catch(e){setMsg(e.message);}finally{setBusy("");}}
 const filtered=useMemo(()=>payments.filter(p=>(filter==="all"||p.status===filter)&&(!search||String(p.device_id||"").toLowerCase().includes(search.toLowerCase())||String(p.id).includes(search))),[payments,filter,search]);
 if(!ready)return <main><section className="card">Loading admin…</section></main>;
 if(!ok)return <main><section className="card auth adminLogin"><h1>Admin sign in</h1><p>Use the private password configured in Vercel.</p><form onSubmit={login}><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" required/><button className="primary wide" disabled={busy==="login"}>{busy==="login"?"Signing in…":"Sign in"}</button></form>{msg&&<p className="hint">{msg}</p>}<p className="hint"><a href="/">Back to Dbweb</a></p></section></main>;
 return <main className="adminDashboard"><header><div><h1>Admin dashboard</h1><p>Payments, redeem codes and manual access management.</p></div><div className="adminTopActions"><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>Refresh</button><button className="secondary" onClick={async()=>{await fetch("/api/admin/session",{method:"DELETE"});setOk(false);}}><LogOut size={15}/>Log out</button></div></header>
 {msg&&<div className="adminNotice">{msg}<button className="iconBtn" onClick={()=>setMsg("")} aria-label="Dismiss"><X size={15}/></button></div>}
 <div className="adminStats"><div className="card"><span><Wallet size={16}/>Total payments</span><strong>{payments.length}</strong></div><div className="card"><span><Clock3 size={16}/>Pending reviews</span><strong>{payments.filter(p=>p.status==="pending").length}</strong></div><div className="card"><span><Check size={16}/>Approved</span><strong>{payments.filter(p=>p.status==="approved").length}</strong></div><div className="card"><span><Gift size={16}/>Redeem codes</span><strong>{codes.length}</strong></div></div>
 <div className="adminTabs">{[["overview","Payments"],["devices","Devices"],["codes","Redeem codes"],["grant","Give access"],["protected","Protected numbers"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="overview"&&<section className="card"><div className="adminSectionHead"><div><h2>Payment reviews</h2><p>Approve only after verifying the receipt and payment.</p></div></div><div className="adminFilters"><label className="adminSearch"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search device ID or payment #"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>{loading?<p>Loading payments…</p>:filtered.length===0?<p className="hint">No payments match this filter.</p>:<div className="adminList">{filtered.map(p=><div className="adminItem" key={p.id}><div className="adminPaymentInfo"><b>Payment #{p.id} · ₹{p.amount} · {p.plan_days} day(s)</b><p className="adminDevice">{p.device_id}</p><p>{p.status} · {p.created_at?new Date(p.created_at).toLocaleString():""}</p></div><div className="adminActions">{p.receipt_url&&<a className="secondary" href={p.receipt_url} target="_blank" rel="noreferrer">View receipt</a>}{p.status==="pending"&&<><button className="primary" disabled={!!busy} onClick={()=>act(p.id,"approve")}><Check size={14}/>Approve</button><button className="secondary" disabled={!!busy} onClick={()=>act(p.id,"reject")}><X size={14}/>Reject</button></>}</div></div>)}</div>}</section>}
 {tab==="devices"&&<section className="card"><div className="adminSectionHead"><div><h2>All device accounts</h2><p>Showing up to 2,000 devices with account, plan, terms, payment and lookup activity.</p></div></div><div className="adminFilters"><label className="adminSearch"><Search size={15}/><input value={deviceSearch} onChange={e=>setDeviceSearch(e.target.value)} placeholder="Search device UUID or plan"/></label></div>{devices.filter(d=>!deviceSearch||d.device_id.toLowerCase().includes(deviceSearch.toLowerCase())||String(d.plan||"").toLowerCase().includes(deviceSearch.toLowerCase())).length===0?<p className="hint">No devices found.</p>:<div className="adminList">{devices.filter(d=>!deviceSearch||d.device_id.toLowerCase().includes(deviceSearch.toLowerCase())||String(d.plan||"").toLowerCase().includes(deviceSearch.toLowerCase())).map(d=><div className="adminItem" key={d.device_id}><div className="adminPaymentInfo"><b>{d.device_id}</b><p>Plan: {d.plan||"free"} · Credits: {d.credits}</p><p>Premium expiry: {d.plan_expires_at?new Date(d.plan_expires_at).toLocaleString():"None"}</p><p>Created: {d.created_at?new Date(d.created_at).toLocaleString():"Unknown"} · Updated: {d.updated_at?new Date(d.updated_at).toLocaleString():"Unknown"}</p><p>Terms accepted: {d.terms_accepted?"Yes ("+(d.terms_version||"current")+")":"No"}{d.terms_accepted_at?" · "+new Date(d.terms_accepted_at).toLocaleString():""}</p><p>Lookups: {d.lookup_count} · Last lookup: {d.last_lookup_at?new Date(d.last_lookup_at).toLocaleString():"None"}</p><p>Payments: {d.payment_count} · Approved: {d.approved_payments} · Pending: {d.pending_payments}</p></div><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(d.device_id);setMsg("Device ID copied.");}catch{setMsg("Copy failed; select the ID manually.");}}}><Copy size={14}/>Copy ID</button></div>)}</div>}</section>}
 {tab==="codes"&&<div className="adminTwoCol"><section className="card"><h2>Create redeem code</h2><p className="hint">Codes can grant credits, premium days, or both.</p><form className="adminForm" onSubmit={createCode}><label>Credits to grant<input type="number" min="0" max="100000" value={codeForm.credits_grant} onChange={e=>setCodeForm({...codeForm,credits_grant:e.target.value})}/></label><label>Premium days<input type="number" min="0" max="3650" value={codeForm.premium_days} onChange={e=>setCodeForm({...codeForm,premium_days:e.target.value})}/></label><label>Maximum redemptions<input type="number" min="1" max="10000" value={codeForm.max_uses} onChange={e=>setCodeForm({...codeForm,max_uses:e.target.value})} required/></label><label>Expiry (optional)<input type="datetime-local" value={codeForm.expires_at} onChange={e=>setCodeForm({...codeForm,expires_at:e.target.value})}/></label><button className="primary wide" disabled={busy==="code"}><Gift size={15}/>{busy==="code"?"Creating…":"Create code"}</button></form>{newCode&&<div className="generatedCode"><span>Copy this code now</span><strong>{newCode}</strong><button className="secondary wide" onClick={async()=>{try{await navigator.clipboard.writeText(newCode);setMsg("Redeem code copied.");}catch{setMsg("Select and copy the code manually.");}}}><Copy size={15}/>Copy code</button></div>}</section><section className="card"><h2>Recent codes</h2><p className="hint">Full codes are never stored or shown again after creation.</p>{codes.length===0?<p className="hint">No codes created yet.</p>:<div className="adminList">{codes.map((c,i)=><div className="adminCodeRow" key={c.code_preview+"-"+i}><b>{c.code_preview}</b><p>{c.credits_grant} credits · {c.premium_days} premium day(s)</p><p>{c.uses_count}/{c.max_uses} uses · {c.active?"Active":"Inactive"}</p><small>{c.expires_at?"Expires "+new Date(c.expires_at).toLocaleString():"No expiry"}</small></div>)}</div>}</section></div>}
 {tab==="protected"&&<section className="card adminGrant"><h2>Protect a phone number</h2><p className="hint">Protected numbers are blocked before the lookup API is called.</p><form className="adminForm" onSubmit={protectAdminNumber}><label>Phone number<input value={protectedPhone} onChange={e=>setProtectedPhone(e.target.value)} inputMode="tel" placeholder="10–15 digits" required/></label><button className="primary wide" disabled={busy==="protect"}>{busy==="protect"?"Protecting…":"Protect number"}</button></form><h2>Currently protected</h2>{protectedNumbers.length===0?<p className="hint">No protected numbers yet.</p>:<div className="adminList">{protectedNumbers.map(n=><div className="adminItem" key={n.id}><div><b>{n.phone_digits}</b><p>{n.protected_by==="admin"?"Protected by admin":"Protected by premium user"}</p></div><button className="secondary" disabled={!!busy} onClick={()=>unprotectNumber(n.phone_digits)}>Remove protection</button></div>)}</div>}</section>}
 {tab==="grant"&&<section className="card adminGrant"><h2>Give someone credits or premium</h2><p className="hint">Enter the user's device ID from their Settings page. This change is applied directly and does not require a redeem code.</p><form className="adminForm" onSubmit={giveAccess}><label>Device UUID<input value={grant.device_id} onChange={e=>setGrant({...grant,device_id:e.target.value.trim()})} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" required pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89a-fA-F][0-9a-fA-F]{3}-[0-9a-fA-F]{12}"/></label><label>Add credits<input type="number" min="0" max="100000" value={grant.credits} onChange={e=>setGrant({...grant,credits:e.target.value})}/></label><label>Premium days to add<input type="number" min="0" max="3650" value={grant.premium_days} onChange={e=>setGrant({...grant,premium_days:e.target.value})}/></label><button className="primary wide" disabled={busy==="grant"}><ShieldCheck size={15}/>{busy==="grant"?"Applying…":"Give access"}</button></form><p className="hint">At least one of credits or premium days must be greater than zero. Granting premium extends any currently active expiry.</p></section>}
 <p className="hint adminBack"><a href="/">Return to Dbweb</a></p></main>;
}